# Generated by Django 5.2.7 on 2025-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_otp_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_request_count',
            field=models.IntegerField(default=0),
        ),
    ]
